DELETE FROM entidades_participantes;
DELETE FROM proyecto;
DELETE FROM datos_generales;
DELETE FROM entidades_asociadas;
DELETE FROM actividades_infraestructura_beneficios;
DELETE FROM fondos_recibidos_del_estado;
DELETE FROM proyectos_financiados_ip;
DELETE FROM competitividad_empresarial;
DELETE FROM diagnostico;